[package]
name = "x"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem extended cargo tasks"
edition = "2018"
publish = false
license = "Apache-2.0"

[dependencies]
camino = "1.0.3"
cargo_metadata = "0.14.0"
determinator = "0.5.1"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.21"
anyhow = "1.0.38"
colored-diff = "0.2.2"
guppy = { version = "0.10.1", features = ["summaries"] }
hakari = "0.4.1"
indoc = "1.0.3"
toml = "0.5.8"
env_logger = "0.8.3"
log = "0.4.14"
chrono = "0.4.19"
globset = "0.4.6"
regex = "1.4.3"
rayon = "1.5.0"
nextest-runner = { git = "https://github.com/diem/diem-devtools", rev = "878ad31ea3268e7496e6e2406329fbd005685a9e" }
indexmap = "1.6.2"
x-core = { path = "../x-core" }
x-lint = { path = "../x-lint" }
