// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	common "github.com/hyperledger/fabric/protos/common"
	mock "github.com/stretchr/testify/mock"
)

// ConfigUpdateProposer is an autogenerated mock type for the ConfigUpdateProposer type
type ConfigUpdateProposer struct {
	mock.Mock
}

// ProposeConfigUpdate provides a mock function with given fields: channel, configtx
func (_m *ConfigUpdateProposer) ProposeConfigUpdate(channel string, configtx *common.Envelope) (*common.ConfigEnvelope, error) {
	ret := _m.Called(channel, configtx)

	var r0 *common.ConfigEnvelope
	if rf, ok := ret.Get(0).(func(string, *common.Envelope) *common.ConfigEnvelope); ok {
		r0 = rf(channel, configtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ConfigEnvelope)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *common.Envelope) error); ok {
		r1 = rf(channel, configtx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
