[package]
name = "diem-transactional-test-harness"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Transactional testing framework for Move"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.6.1"
once_cell = "1.7.2"
anyhow = "1.0.38"
structopt = "0.3.21"
bcs = "0.1.2"

move-transactional-test-runner = { path = "../transactional-test-runner" }
language-e2e-tests = { path = "../e2e-tests" }
move-lang = { path = "../../move-lang" }
move-binary-format = { path = "../../move-binary-format" }
move-core-types = { path = "../../move-core/types" }
diem-vm =  { path = "../../../diem-move/diem-vm" }
diem-types = { path = "../../../types", features = ["fuzzing"] }
diem-transaction-builder = { path = "../../../sdk/transaction-builder" }
diem-crypto = { path = "../../../crates/diem-crypto" }
diem-framework = { path = "../../../diem-move/diem-framework" }
diem-keygen = { path = "../../../diem-move/diem-keygen" }
diem-state-view = { path = "../../../storage/state-view" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
move-command-line-common = { path = "../../move-command-line-common" }
vm-genesis= { path = "../../../diem-move/vm-genesis" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[test]]
name = "tests"
harness = false
