[package]
name = "disassembler"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
colored = "2.0.0"

bytecode-verifier = { path = "../../bytecode-verifier" }
bytecode-source-map = { path = "../../move-ir-compiler/bytecode-source-map" }
move-command-line-common = { path = "../../move-command-line-common" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
move-core-types = { path = "../../move-core/types" }
move-ir-types = { path = "../../move-ir/types" }
move-binary-format = { path = "../../move-binary-format" }
move-coverage = { path = "../move-coverage" }
move-lang = { path = "../../move-lang" }

structopt = "0.3.21"

[features]
default = []
