[package]
name = "diem-transaction-benchmarks"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem transaction benchmarks"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
criterion = "0.3.4"
proptest = "1.0.0"
criterion-cpu-time = "0.1.0"

diem-types = { path = "../../types", features = ["fuzzing"] }
language-e2e-tests = { path = "../../language/testing-infra/e2e-tests" }
diem-workspace-hack = { path = "../../common/workspace-hack" }

read-write-set = { path = "../../language/tools/read-write-set" }
read-write-set-dynamic = { path = "../../language/tools/read-write-set/dynamic" }
diem-vm = { path = "../diem-vm" }
diem-framework-releases = { path = "../diem-framework/DPN/releases" }

[[bench]]
name = "transaction_benches"
harness = false
