[package]
name = "shuffle-custom-move-code"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
diem-framework = { path = "../../diem-move/diem-framework" }
diem-workspace-hack = { path = "../../common/workspace-hack" }
diem-vm = { path = "../../diem-move/diem-vm" }
move-stdlib = { path = "../../language/move-stdlib" }
move-unit-test = { path = "../../language/tools/move-unit-test" }
