[package]
name = "generate-format"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem types"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
rand = "0.8.3"
serde = { version = "1.0.124", features = ["derive"] }
serde-reflection = "0.3.2"
serde_yaml = "0.8.17"
structopt = "0.3.21"

consensus = { path = "../../consensus", features=["fuzzing"] }
consensus-types = { path = "../../consensus/consensus-types", features=["fuzzing"] }
bcs = "0.1.2"
diem-config = { path = "../../config" }
diem-crypto = { path = "../../crypto/crypto", features=["fuzzing"] }
diem-crypto-derive = { path = "../../crypto/crypto-derive"}
diem-types = { path = "../../types", features=["fuzzing"] }
diem-workspace-hack = { path = "../../common/workspace-hack" }
network = { path = "../../network" }
move-core-types = { path = "../../language/move-core/types", features=["fuzzing"] }

[[bin]]
name = "compute"
path = "src/compute.rs"
test = false
