[package]
name = "storage-service-server"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "The Diem storage service (server-side)"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.2"
bytes = "1.0.1"
futures = "0.3.12"
once_cell = "1.7.2"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
tokio = { version = "1.8.1", features = ["rt", "macros"], default-features = false }

bounded-executor = { path = "../../../common/bounded-executor" }
channel = { path = "../../../common/channel" }
diem-config = { path = "../../../config" }
diem-logger = { path = "../../../common/logger" }
diem-metrics = { path = "../../../common/metrics" }
diem-types = { path = "../../../types" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
network = { path = "../../../network" }
storage-interface = { path = "../../../storage/storage-interface" }
storage-service-types = { path = "../types" }

[dev-dependencies]
anyhow = "1.0.38"
claim = "0.5.0"

diem-crypto = { path = "../../../crates/diem-crypto" }
diem-types = { path = "../../../types" }
move-core-types = { path = "../../../language/move-core/types" }
storage-interface = { path = "../../../storage/storage-interface" }
