[package]
name = "diem-id-generator"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem diem-id-generator. A common id generator for Diem"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
diem-workspace-hack = { path = "../workspace-hack" }
