[package]
name = "module-generation"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem binary module generation"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
rand = "0.8.3"

bytecode-verifier = { path = "../../bytecode-verifier" }
ir-to-bytecode = { path = "../../compiler/ir-to-bytecode" }
move-core-types = { path = "../../move-core/types" }
move-ir-types = { path = "../../move-ir/types" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
move-binary-format = { path = "../../move-binary-format" }

[features]
default = []
