[package]
name = "move-package"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
petgraph = "0.5.1"
anyhow = "1.0.40"
walkdir = "2.3.1"
structopt = "0.3.21"
bcs = "0.1.2"
colored = "2.0.0"
serde_yaml = "0.8.17"
tempfile = "3.2.0"
sha2 = "0.9.3"
regex = "1.1.9"

diem-workspace-hack = { path = "../../../common/workspace-hack" }
move-binary-format = { path = "../../move-binary-format" }
move-lang = { path = "../../move-lang" }
bytecode-source-map = { path = "../../move-ir-compiler/bytecode-source-map" }
abigen = { path = "../../move-prover/abigen" }
docgen = { path = "../../move-prover/docgen" }
errmapgen = { path = "../../move-prover/errmapgen" }
move-core-types = { path = "../../move-core/types" }
move-symbol-pool = { path = "../../move-symbol-pool" }
move-command-line-common = { path = "../../move-command-line-common" }
move-model = { path = "../../move-model" }
move-bytecode-utils = { path = "../move-bytecode-utils" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[test]]
name = "test_runner"
harness = false
