[package]
name = "diem-api"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem REST API"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bcs = "0.1.2"
bytes = "1.0.1"
futures = "0.3.12"
hex = "0.4.3"
hyper = "0.14.4"
once_cell = "1.7.2"
percent-encoding = "2.1.0"
serde = { version = "1.0.124", features = ["derive"], default-features = false }
serde_json = "1.0.64"
tokio = { version = "1.8.1", features = ["full"] }
warp = { version = "0.3.0", features = ["default"] }

diem-config = { path = "../config" }
diem-crypto = { path = "../crates/diem-crypto" }
diem-json-rpc = { path = "../json-rpc" }
diem-logger = { path = "../common/logger" }
diem-mempool = { path = "../mempool"}
diem-metrics = { path = "../common/metrics" }
diem-types = { path = "../types" }
diem-workspace-hack = { path = "../common/workspace-hack" }
diem-api-types = { path = "./types", package = "diem-api-types" }
storage-interface = { path = "../storage/storage-interface" }
move-core-types = { path = "../language/move-core/types" }
resource-viewer = { path = "../language/tools/resource-viewer" }

[dev-dependencies]
rand = "0.8.3"
reqwest = { version = "0.11.2", features = ["blocking", "json"], default_features = false }

mempool-notifications = { path = "../state-sync/inter-component/mempool-notifications" }
diemdb = { path = "../storage/diemdb", features = ["fuzzing"] }
diem-crypto = { path = "../crates/diem-crypto" }
diem-global-constants = { path = "../config/global-constants" }
diem-mempool = { path = "../mempool", features = ["fuzzing"] }
diem-secure-storage = { path = "../secure/storage" }
diem-temppath = { path = "../common/temppath" }
diem-genesis-tool = {path = "../config/management/genesis", features = ["testing"] }
diem-framework-releases = { path = "../diem-move/diem-framework/DPN/releases" }
diem-sdk = { path = "../sdk" }
vm-validator = { path = "../vm-validator" }
diem-vm = { path = "../diem-move/diem-vm" }
executor = { path = "../execution/executor" }
executor-types = { path = "../execution/executor-types" }
