[package]
name = "vm-genesis"
version = "0.1.0"
edition = "2018"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem vm genesis"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.38"
once_cell = "1.7.2"
rand = "0.8.3"

bytecode-verifier = { path = "../../language/bytecode-verifier" }
bcs = "0.1.2"
diem-config = { path = "../../config" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-state-view = { path = "../../storage/state-view" }
diem-types = { path = "../../types" }
diem-workspace-hack = { path = "../../common/workspace-hack" }
move-bytecode-utils = { path = "../../language/tools/move-bytecode-utils" }
move-core-types = { path = "../../language/move-core/types" }
move-vm-runtime = { path = "../../language/move-vm/runtime"}
move-vm-types = { path = "../../language/move-vm/types" }
diem-framework = { path = "../../diem-move/diem-framework" }
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }
diem-transaction-builder = { path = "../../sdk/transaction-builder"}
move-binary-format = { path = "../../language/move-binary-format" }
diem-vm = { path = "../diem-vm" }
read-write-set = { path = "../../language/tools/read-write-set" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
diem-proptest-helpers = { path = "../../common/proptest-helpers" }

[features]
default = []
fuzzing = ["diem-types/fuzzing", "move-vm-types/fuzzing"]
