[package]
name = "DiemExperimental"
version = "1.5.0"

[addresses]
Std = "0x1"
DiemFramework = "0x1"
BARS = "0x34CD440B72D03907100007D7BC0080A1"
DiemRoot = "0xA550C18"
TreasuryCompliance = "0xB1E55ED"
CurrencyInfo = "0xA550C18"
VMReserved = "0x0"

[dependencies]
MoveStdlib = { local = "../../../language/move-stdlib" }
