[package]
name = "diem-client"
version = "0.0.3"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem JSON-RPC/Rest client"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2018"

[features]
default = ["async", "blocking", "faucet", "websocket"]
blocking = ["ureq", "ipnet"]
async = ["reqwest", "tokio"]
faucet = ["reqwest", "reqwest/blocking", "blocking"]
websocket = ["async", "futures", "tokio-tungstenite"]

[dependencies]
anyhow = "1.0.38"
bcs = "0.1.2"
hex = "0.4.3"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
tracing = "0.1.26"
url = "2.2.2"

diem-crypto = { path = "../diem-crypto", version = "0.0.3" }
diem-json-rpc-types = { path = "../../json-rpc/types", version = "0.0.3" }
move-core-types = { path = "../../language/move-core/types", version = "0.0.3" }
diem-types = { path = "../../types", version = "0.0.3" }

# Optional Dependencies
futures = {version = "0.3.12", optional = true }
reqwest = { version = "0.11.2", features = ["json"], optional = true }
tokio = { version = "1.8.1", features = ["time"], default_features = false, optional = true }
tokio-tungstenite = { version = "0.14", optional = true }
ureq = { version = "1.5.4", features = ["json", "native-tls"], default-features = false, optional = true }
ipnet = { version = "2.3", optional = true }

# Needed to fsync a directory on Windows apparently...
[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[dev-dependencies]
diem-types = { path = "../../types", version = "0.0.3", features = ["fuzzing"] }
diem-workspace-hack = { path = "../../common/workspace-hack" }
proptest = "1.0.0"
tempfile = "3.2.0"
