apiVersion: v1
kind: Service
metadata:
  name: {pod_name}
  labels:
    app: diem-lsr
    diem-node: "true"
    peer_id: {pod_name}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app: diem-lsr
    diem-node: "true"
    peer_id: {pod_name}
  ports:
  - name: safety-rules
    protocol: TCP
    port: 6185
