apiVersion: v1
kind: Pod
metadata:
  name: {pod_name}
  labels:
    app: diem-lsr
    diem-node: "true"
    peer_id: {pod_name}
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  serviceAccountName: clustertest
  nodeSelector:
    nodeType: validators
  nodeName: "{node_name}"
  containers:
    - name: fluent-bit
      image: 853397791086.dkr.ecr.us-west-2.amazonaws.com/fluent-bit:1.3.9
      imagePullPolicy: IfNotPresent
      command: ["/fluent-bit/bin/fluent-bit", "-c", "/opt/diem/data/fluent-bit/fluent-bit.conf"]
      volumeMounts:
      - mountPath: /opt/diem/data
        name: diem-data
    - name: main
      image: 853397791086.dkr.ecr.us-west-2.amazonaws.com/diem/validator_tcb:{image_tag}
      imagePullPolicy: Always
      command: ["/opt/diem/bin/safety-rules", "/opt/diem/etc/node.yaml"]
      ports:
        - containerPort: 6185
      volumeMounts:
        - mountPath: /opt/diem/etc
          name: config-built
        - mountPath: /opt/diem/data
          name: diem-data
        - mountPath: /opt/vault
          name: vault-token
      env:
        - name: RUST_LOG
          value: debug
        - name: RUST_BACKTRACE
          value: "1"
        - name: PUSH_METRICS_ENDPOINT
          value: "http://diem-testnet-prometheus-pushgateway:9091/metrics/job/safety_rules/instance/{pod_name}"
  volumes:
    - name: config-built
      hostPath:
        path: /config
        type: DirectoryOrCreate
    - name: diem-data
      hostPath:
        path: /data
        type: DirectoryOrCreate
    - name: tmp
      emptyDir: {{}}
    - name: vault-token
      emptyDir:
        medium: Memory
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: diem-node
                operator: Exists
          topologyKey: "kubernetes.io/hostname"
  terminationGracePeriodSeconds: 5
  tolerations:
    - key: "validators"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node.kubernetes.io/not-ready"
      operator: "Exists"
      effect: "NoSchedule"
