# This compose file defines a Public Fullnode docker compose wrapper around diem-node.
#
# In order to use, place a copy of the proper genesis.blob and waypoint.txt in this directory.
#
# Note this compose comes with a pre-configured node.config for fullnodes, see
# public_full_node.yaml. The config is pretty well documented and aligns with instructions herein.
# It is intended for use with testnet but can be easily modified for other systems.
#
# Testnet genesis and waypoint can be acquired at the following URLs:
# * https://testnet.diem.com/genesis.blob
# * https://testnet.diem.com/waypoint.txt
# Testnet's genesis does not support onchain discovery and also requires a seed_addrs to be added
# to the full_node_networks and the discovery method to be set to "none" (this step has been
# completed):
#     discovery_method: "none"
#     seed_addrs:
#         4223dd0eeb0b0d78720a8990700955e1:
#             - "/dns4/fn.testnet.diem.com/tcp/6182/ln-noise-ik/b6fd31624af370085cc3f872437bb4d9384b31a11b33b9591ddfaaed5a28b613/ln-handshake/0"
#
# TODO:
#   * Directions on the correct image
#   * Connecting to the local testnet
#
# Additional information:
# * If you use this compose for different Diem Networks, you will need remove the db volume first.
# * Diem's testnet produces approximately 3 GB worth of chain data per day, so be patient while
# starting for the first time. As a sanity check, enter the container and check the increasing size
# of the db:
#   * `docker exec -it $CONTAINER_ID /bin/bash`
#   * `du -csm /opt/diem/data``
#
# Monitoring:
# If you want to install the monitoring components for your fullnode
# you can symlink the ../monitoring folder into this directory.
# Note that you will need to rename the monitoring docker-compose.yaml file to avoid duplication.
# e.g. rename it to docker-compose.mon.yaml and run:
# `docker-compose -f docker-compose.yaml -f docker-compose.mon.yaml up -d`
# Dashboard can be accessed locally by loading localhost:3000 on your browser
version: "3.8"
services:
  fullnode:
    image: diem/validator:devnet
    volumes:
      - type: volume
        source: db
        target: /opt/diem/data
      - type: bind
        source: ./genesis.blob
        target: /opt/diem/etc/genesis.blob
        read_only: true
      - type: bind
        source: ./public_full_node.yaml
        target: /opt/diem/etc/node.yaml
        read_only: true
      - type: bind
        source: ./waypoint.txt
        target: /opt/diem/etc/waypoint.txt
        read_only: true
    command: ["/opt/diem/bin/diem-node", "-f", "/opt/diem/etc/node.yaml"]
    ports:
      - "8080:8080"
    expose:
      - 9101
volumes:
  db:
