base:
    # This is the location Diem will store its database. It is backed by a dedicated docker volume
    # for persistence.
    data_dir: "/opt/diem/data"
    role: "full_node"
    waypoint:
        # This is a checkpoint into the blockchain for added security.
        from_file: "/opt/diem/etc/waypoint.txt"

execution:
    # Path to a genesis transaction. Note, this must be paired with a waypoint. If you update your
    # waypoint without a corresponding genesis, the file location should be an empty path.
    genesis_file_location: "/opt/diem/etc/genesis.blob"

full_node_networks:
      # Disabled for testnet
    - discovery_method: "none"
      # The network must have a listen address to specify protocols. This runs it locally to
      # prevent remote, incoming connections.
      listen_address: "/ip4/127.0.0.1/tcp/6180"
      network_id: "public"
      # Testnet does not have the right discovery entry points on-chain so this is used instead
      seeds:
        D4C4FB4956D899E55289083F45AC5D84:
          addresses:
            - "/dns4/fn.testnet.diem.com/tcp/6182/ln-noise-ik/d29d01bed8ab6c30921b327823f7e92c63f8371456fb110256e8c0e8911f4938/ln-handshake/0"
          role: "ValidatorFullNode"

json_rpc:
    # This specifies your JSON-RPC endpoint. Intentionally on public so that Docker can export it.
    address: 0.0.0.0:8080
