name: (hyperjump) labels

on:
  repository_dispatch:
    types: [labels]

jobs:
  labels:
    runs-on: ubuntu-latest
    name: (hyperjump) labels
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: labels
        uses: diem/actions/hyperjump-labels@a5fa31ff2b54a544cd88ac912cda469742592e6c
        with:
          github-token: ${{ secrets.HYPERJUMP_TOKEN }}
          number: ${{ github.event.client_payload.number }}
          add: ${{ join(github.event.client_payload.add) }}
          remove: ${{ join(github.event.client_payload.remove) }}
