name: (hyperjump) comment

on:
  repository_dispatch:
    types: [comment]

jobs:
  comment:
    runs-on: ubuntu-latest
    name: (hyperjump) comment
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: comment
        uses: diem/actions/hyperjump-comment@a5fa31ff2b54a544cd88ac912cda469742592e6c
        with:
          github-token: ${{ secrets.HYPERJUMP_TOKEN }}
          number: ${{ github.event.client_payload.number }}
          comment: ${{ github.event.client_payload.comment }}
          tag: ${{ github.event.client_payload.tag }}
          delete-older: ${{ github.event.client_payload.delete_older }}
