[package]
name = "diem-fuzz"
version = "0.1.0"
edition = "2018"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem fuzzer fuzz"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.3.2"
diem-fuzzer = { path = ".." }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
once_cell = "1.7.2"

# Prevent this from interfering with workspaces

[[bin]]
name = "fuzz_runner"
path = "fuzz_targets/fuzz_runner.rs"
test = false

# used for integration with Google OSS-Fuzz (see README)
[[bin]]
name = "fuzzer_builder"
path = "google-oss-fuzz/fuzzer_builder.rs"
test = false
