[package]
name = "genesis-viewer"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem genesis viewer"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.2"
diem-types = { path = "../../../types" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
move-binary-format = { path = "../../move-binary-format" }
diem-resource-viewer = { path = "../diem-resource-viewer"}
vm-genesis = { path = "../vm-genesis" }
diem-framework-releases = { path = "../../diem-framework/releases" }
move-vm-runtime = { path = "../../move-vm/runtime" }
move-vm-test-utils = { path = "../../move-vm/test-utils" }

structopt = "0.3.21"
