[package]
name = "diem-writeset-generator"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Generating writesets used for incident management"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
structopt = "0.3.21"
tempfile = "3.2.0"
handlebars = "3.5.3"
hex = "0.4.3"
serde = { version = "1.0.124", default-features = false }
serde_json = "1.0.64"
once_cell = "1.7.2"

bytecode-verifier = { path = "../../language/bytecode-verifier" }
diem-workspace-hack = { path = "../../common/workspace-hack" }
diem-crypto-derive = { path = "../../crates/diem-crypto-derive" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-types = { path = "../../types" }
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }
diem-framework = { path = "../../diem-move/diem-framework" }
move-lang = { path = "../../language/move-lang" }
bcs = "0.1.2"
diem-state-view = { path = "../../storage/state-view" }
diem-validator-interface = { path = "../diem-validator-interface" }
diem-transaction-replay = { path = "../transaction-replay" }
diemdb = { path = "../../storage/diemdb" }
diem-vm = { path = "../diem-vm" }
move-binary-format = { path = "../../language/move-binary-format"}
move-vm-types = { path = "../../language/move-vm/types" }
move-core-types = { path = "../../language/move-core/types" }
move-vm-runtime = { path = "../../language/move-vm/runtime" }
move-vm-test-utils = { path = "../../language/move-vm/test-utils" }
read-write-set = { path = "../../language/tools/read-write-set" }
