[package]
name = "shuffle"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "CLI frontend for Shuffle"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bcs = "0.1.2"
directories = "4.0.1"
hex = "0.4.3"
include_dir = { version = "0.6.0", features = ["glob"] }
once_cell = "1.7.2"
rand = "0.8.4"
reqwest = { version = "0.11.2", features = ["blocking", "json"] }
serde = { version = "1.0.124", features = ["derive"] }
structopt = "0.3.21"
tempfile = "3.2.0"
tokio = { version = "1.8.1", features = ["full"] }
toml = "0.5.8"
url = { version = "2.2.2" }

abigen = { path = "../../language/move-prover/abigen" }
diem-api-types = { path = "../../api/types" }
diem-config = { path = "../../config" }
diem-crypto = { path = "../../crates/diem-crypto" }
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }
diem-genesis-tool = { path = "../../config/management/genesis" }
diem-infallible = { path = "../../common/infallible"}
diem-json-rpc-types = { path = "../../json-rpc/types" }
diem-node = { path = "../../diem-node" }
diem-sdk = { path = "../../sdk" }
diem-types = { path = "../../types" }
diem-vm = { path = "../../diem-move/diem-vm" }
diem-workspace-hack = { path = "../../common/workspace-hack" }
diemdb = { path = "../../storage/diemdb" }
generate-key = { path = "../../config/generate-key" }
move-binary-format = { path = "../../language/move-binary-format" }
move-cli = { path = "../../language/tools/move-cli" }
move-core-types = { path = "../../language/move-core/types" }
move-lang = { path = "../../language/move-lang" }
move-package = { path = "../../language/tools/move-package" }
move-unit-test = { path = "../../language/tools/move-unit-test" }
serde-generate = "0.20.2"
serde-reflection = "0.3.4"
serde_json = "1.0.68"
serde_yaml = "0.8.17"
transaction-builder-generator = { path = "../../diem-move/transaction-builder-generator" }

[[bin]]
name = "shuffle"
path = "src/main.rs"
