[package]
name = "event-notifications"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/diem/diem"
description = "The notification service offered by state sync for on-chain events"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.12"
itertools = { version = "0.10.0", default-features = false }
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
tokio = { version = "1.8.1" }

channel = { path = "../../../common/channel" }
diem-id-generator = { path = "../../../common/id-generator" }
diem-infallible = { path = "../../../common/infallible" }
diem-types = { path = "../../../types" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
storage-interface = { path = "../../../storage/storage-interface" }


[dev-dependencies]
bcs = "0.1.2"
claim = "0.5.0"

diem-crypto = { path = "../../../crates/diem-crypto" }
diem-temppath = { path = "../../../common/temppath" }
diem-vm = { path = "../../../diem-move/diem-vm" }
diemdb = { path = "../../../storage/diemdb" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers" }
move-core-types = { path = "../../../language/move-core/types" }
vm-genesis = { path = "../../../diem-move/vm-genesis", features = ["fuzzing"] }
