[package]
name = "shuffle-integration-tests"
version = "0.0.0"
authors = ["Diem Association <opensource@diem.com>"]
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bcs = "0.1.2"
hex = "0.4.3"
reqwest = { version = "0.11.2", features = ["blocking", "json"], default_features = false }
serde_json = "1.0.64"
tempfile = "3.2.0"
tokio = { version = "1.8.1", features = ["full"] }
url = { version = "2.2.2" }

generate-key = { path = "../../config/generate-key" }
diem-json-rpc-types = { path = "../../json-rpc/types" }
diem-sdk = { path = "../../sdk" }
diem-types = { path = "../../types" }
diem-workspace-hack = { path = "../../common/workspace-hack" }
forge = { path = "../../testsuite/forge" }
move-cli = { path = "../../language/tools/move-cli" }
shuffle = { path = "../cli" }
smoke-test = { path = "../../testsuite/smoke-test" }

[[test]]
name = "shuffle-forge"
harness = false
