[package]
name = "consensus-types"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
itertools = "0.10.0"
mirai-annotations = { version = "1.10.1", default-features = false }
proptest = { version = "1.0.0", optional = true }
serde = { version = "1.0.124", default-features = false }

executor-types = { path = "../../execution/executor-types" }
bcs = "0.1.2"
diem-crypto = { path = "../../crates/diem-crypto" }
diem-crypto-derive = { path = "../../crates/diem-crypto-derive" }
diem-infallible = { path = "../../common/infallible" }
diem-types = { path = "../../types" }
diem-workspace-hack = { path = "../../common/workspace-hack" }
short-hex-str = { path = "../../common/short-hex-str" }


[dev-dependencies]
proptest = "1.0.0"
serde_json = "1.0.64"

diem-types = { path = "../../types", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "diem-types/fuzzing", "diem-crypto/fuzzing"]
