[package]
name = "move-bytecode-viewer"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
structopt = "0.3.21"
anyhow = "1.0.38"
regex = "1.1.9"
termion = "1.5"
tui = "0.14.0"

move-command-line-common = { path = "../../move-command-line-common" }
bytecode-source-map = { path = "../../move-ir-compiler/bytecode-source-map" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
move-ir-types = { path = "../../move-ir/types" }
move-binary-format = { path = "../../move-binary-format" }
disassembler = { path = "../disassembler" }


[features]
default = []
