# This is a basic workflow to help you get started with Actions

name: Preliminary_checks

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the release-1.4-BFT-3 branch
  push:
    branches: [ release-1.4-BFT-3 ]
  pull_request:
    branches: [ release-1.4-BFT-3 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Preliminary_checks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.12

      - name: Prepare Env
        run: bash ./scripts/prepare_environ.sh

      # Runs a single command using the runners shell
      - name: Checks
        working-directory: /home/runner/go/src/github.com/hyperledger/fabric
        run: bash ./scripts/build_checks.sh

      - name: Post
        working-directory: /home/runner/go/src/github.com/hyperledger/fabric
        run: bash ./scripts/post.sh
