[package]
name = "testcases"
version = "0.0.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "compat tests"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bcs = "0.1.2"
diem-sdk = { path = "../../sdk" }
diem-operational-tool = {path = "../../config/management/operational", features = ["testing"] }
forge = { path = "../forge" }
rand = "0.8.3"
tokio = { version = "1.8.1", features = ["full"] }
diem-logger = { path = "../../common/logger" }
diem-workspace-hack = { path = "../../common/workspace-hack" }

[[test]]
name = "forge-local-compatibility"
harness = false

[[test]]
name = "forge-local-performance"
harness = false
