[package]
name = "mvhashmap"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem VM runtime"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.7.2"
rayon = "1.5.0"
num_cpus = "1.13.0"
diem-workspace-hack = { path = "../../common/workspace-hack" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
