[package]
name = "scratchpad-benchmark"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem executor benchmark"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
itertools = { version = "0.10.0", default-features = false }
rand = "0.8.3"
rayon = "1.5.0"
structopt = "0.3.21"

diemdb = { path = "../diemdb" }
diemdb-benchmark = { path = "../diemdb-benchmark" }
diem-config = { path = "../../config" }
diem-crypto = { path = "../../crypto/crypto" }
diem-genesis-tool = {path = "../../config/management/genesis", features = ["testing"] }
diem-infallible = { path = "../../common/infallible" }
diem-logger = { path = "../../common/logger" }
diem-types = { path = "../../types" }
diem-workspace-hack = { path = "../../common/workspace-hack" }
executor-types = { path = "../../execution/executor-types" }
scratchpad = { path = "..//scratchpad" }
storage-interface = { path = "../storage-interface" }
