[package]
name = "language-e2e-tests"
version = "0.1.0"
edition = "2018"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem language e2e testing framework"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.38"
goldenfile = "1.1.0"
bcs = "0.1.2"
once_cell = "1.7.2"
diem-crypto = { path = "../../../crates/diem-crypto", features = ["fuzzing"] }
rand = "0.8.3"
serde = { version = "1.0.124", default-features = false }
diem-state-view = { path = "../../../storage/state-view" }
diem-types = { path = "../../../types", features = ["fuzzing"] }
diem-writeset-generator = { path = "../../../diem-move/writeset-transaction-generator" }
move-core-types = { path = "../../move-core/types" }
move-ir-compiler = { path = "../../move-ir-compiler" }
move-vm-runtime = { path = "../../move-vm/runtime" }
move-vm-types = { path = "../../move-vm/types" }
move-binary-format = { path = "../../move-binary-format" }
vm-genesis = { path = "../../../diem-move/vm-genesis" }
diem-vm = { path = "../../../diem-move/diem-vm" }
proptest = "1.0.0"
proptest-derive = "0.3.0"
diem-keygen = { path = "../../../diem-move/diem-keygen" }
diem-proptest-helpers = { path = "../../../common/proptest-helpers" }
diem-config = { path = "../../../config" }
diem-framework-releases = { path = "../../../diem-move/diem-framework/DPN/releases" }
diem-workspace-hack = { path = "../../../common/workspace-hack" }
diem-transaction-builder = { path = "../../../sdk/transaction-builder" }
move-command-line-common = { path = "../../move-command-line-common" }
read-write-set = { path = "../../tools/read-write-set" }
hex = "0.4.3"
