[package]
name = "diem-transaction-replay"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Replay transactions stored on chain"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
structopt = "0.3.21"
hex = "0.4.3"
diem-workspace-hack = { path = "../../common/workspace-hack" }
diem-types = { path = "../../types" }
diem-state-view = { path = "../../storage/state-view" }
diem-validator-interface = { path = "../diem-validator-interface" }
diemdb = { path = "../../storage/diemdb" }
diem-vm = { path = "../diem-vm" }
move-binary-format = { path = "../../language/move-binary-format"}
move-cli = { path = "../../language/tools/move-cli" }
move-vm-types = { path = "../../language/move-vm/types" }
move-core-types = { path = "../../language/move-core/types" }
move-vm-runtime = { path = "../../language/move-vm/runtime" }
move-vm-test-utils = { path = "../../language/move-vm/test-utils" }
diem-resource-viewer = { path = "../diem-resource-viewer" }
diem-framework = { path = "../../diem-move/diem-framework" }
move-lang = { path = "../../language/move-lang" }
bcs = "0.1.2"
difference = "2.0.0"

[dev-dependencies]
vm-genesis = { path = "../vm-genesis" }
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }
