[package]
name = "diem-json-rpc-client"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem JSONRPC client"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.3.12"
rand = "0.8.3"

diem-crypto = { path = "../../crypto/crypto" }
diem-json-rpc-types  = { path = "../../json-rpc/types" }
diem-types = { path = "../../types" }
diem-workspace-hack = { path = "../../common/workspace-hack" }
diem-client = { path = "../../sdk/client" }
